package com.araxaprojetosweb.backend.config;

import java.util.Arrays;
import java.util.Date;
import java.util.Random;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;

import com.araxaprojetosweb.backend.entities.Artigo;
import com.araxaprojetosweb.backend.entities.Autor;
import com.araxaprojetosweb.backend.entities.Categoria;
import com.araxaprojetosweb.backend.entities.Comentario;
import com.araxaprojetosweb.backend.entities.Secao;
import com.araxaprojetosweb.backend.entities.Tag;
import com.araxaprojetosweb.backend.entities.enums.ArtigoStatus;
import com.araxaprojetosweb.backend.repositories.ArtigoRepository;
import com.araxaprojetosweb.backend.repositories.AutorRepository;
import com.araxaprojetosweb.backend.repositories.CategoriaRepository;
import com.araxaprojetosweb.backend.repositories.ComentarioRepository;
import com.araxaprojetosweb.backend.repositories.SecaoRepository;
import com.araxaprojetosweb.backend.repositories.TagRepository;
import com.araxaprojetosweb.backend.util.AutenticationBase64;

@Configuration
@Profile("test")
public class SeedConfig implements CommandLineRunner {

	@Autowired
	private AutorRepository autorRepository;
	@Autowired
	private CategoriaRepository categoriaRepository;
	@Autowired
	private ArtigoRepository artigoRepository;
	@Autowired
	private ComentarioRepository comentarioReposiroty;
	@Autowired
	private TagRepository tagRepository;
	@Autowired
	private SecaoRepository secRepository;
	Random r = new Random();

	@Override
	public void run(String... args) throws Exception {

		Categoria cat1 = new Categoria(null, "Portifolio", "Documentos Uteis");
		Categoria cat2 = new Categoria(null, "Blog", "Discursões Sobre Tecnologias");
		Categoria cat3 = new Categoria(null, "Hacker", "Comentarios Hacker Ethical");
		Categoria cat4 = new Categoria(null, "Quarentena", "Virus em quarentena");

		Secao s1 = new Secao(null, "Coleta de Informação", cat3);
		Secao s2 = new Secao(null, "Vulnerabilidades", cat3);
		Secao s3 = new Secao(null, "FingerPrinting", cat3);
		Secao s4 = new Secao(null, "Wireless", cat3);
		Secao s5 = new Secao(null, "Denial of Service", cat3);
		Secao s6 = new Secao(null, "SQL Injection", cat3);
		Secao s7 = new Secao(null, "Cracking", cat3);
		Secao s8 = new Secao(null, "Man in the Middle", cat3);
		Secao s9 = new Secao(null, "Engenharia Social", cat3);
		Secao s10 = new Secao(null, "Pentest", cat3);
		Secao s11 = new Secao(null, "NMAP | Wireshark", cat3);
		Secao s12 = new Secao(null, "Reverse Engineering", cat3);
		Secao s13 = new Secao(null, "Crawlers e Spiders", cat3);

		Secao s14 = new Secao(null, "Malware", cat4);
		Secao s15 = new Secao(null, "Trojan", cat4);
		Secao s16 = new Secao(null, "Ransomware", cat4);
		Secao s17 = new Secao(null, "Virus", cat4);

		Autor a1 = new Autor(null, "Flavio Rogerio", "Primeiro Livro", "semFotoCard.png", "solebac@hotmail.com", "Flavio",
				"$2a$10$Bcb/zFo0yHKWsIuAoTZFAObzXzzHgw3TVe1F1CTpcs5i4S8x3rC6q");
		Autor a2 = new Autor(null, "Lucas Rogerio", "Segundo Livro", "semFotoCard.png", "lucas@hotmail.com", "Lucas",
				"$2a$10$Bcb/zFo0yHKWsIuAoTZFAObzXzzHgw3TVe1F1CTpcs5i4S8x3rC6q");
		categoriaRepository.saveAll(Arrays.asList(cat1, cat2, cat3, cat4));
		secRepository
				.saveAll(Arrays.asList(s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17));
		autorRepository.saveAll(Arrays.asList(a1, a2));
		Artigo art1 = new Artigo(null, "Primeiro Artigo", new Date(),
				"@aaaaaaaaaaaaaaaaaaIntrodução Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Primeiro Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Segundo Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Conclusão Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				ArtigoStatus.PUBLICADO, AutenticationBase64.passwordEncodeBase64(r.nextDouble() + "|" + "React"), "React", "semFotoDestaque.png",
				"semFotoCard.png", a1, 9, cat3, s1);
		Artigo art2 = new Artigo(null, "Segundo Artigo", new Date(),
				"@bbbbbbbbbbbbbbbbbbbbIntrodução Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Primeiro Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Segundo Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Conclusão Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				ArtigoStatus.PUBLICADO, AutenticationBase64.passwordEncodeBase64(r.nextDouble() + "|" + "Mysql"), "Mysql", "semFotoDestaque.png",
				"semFotoCard.png", a2, 6, cat3, s1);
		Artigo art3 = new Artigo(null, "terceiro Artigo", new Date(),
				"@ssssssssssssssssssssssrrrrrrrrrrrrrIntrodução Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Primeiro Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Segundo Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Conclusão Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",			
				ArtigoStatus.RASCUNHO,  
				AutenticationBase64.passwordEncodeBase64(r.nextDouble() + "|" + "Next"),"Next", "semFotoDestaque.png",
				"semFotoCard.png", a2, 5, cat3, s1);
		Artigo art4 = new Artigo(null, "Quarto Artigo", new Date(),
				"@eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeIntrodução Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhPrimeiro Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Segundo Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Conclusão Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",ArtigoStatus.PUBLICADO, 
				 AutenticationBase64.passwordEncodeBase64(r.nextDouble() + "|" + "Google"), "Google","semFotoDestaque.png",
				"semFotoCard.png", a2, 1, cat3, s2);
		Artigo art5 = new Artigo(null, "Quinto Artigo", new Date(),
				"@jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjiiiiiiiiiiiiiiiiiiiiiIntrodução Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Primeiro Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Segundo Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Conclusão Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",ArtigoStatus.PUBLICADO, 
				 AutenticationBase64.passwordEncodeBase64(r.nextDouble() + "|" + "Sql"),"Sql", "semFotoDestaque.png",
				"semFotoCard.png", a2, 4, cat3, s3);
		Artigo art6 = new Artigo(null, "Sexto Artigo", new Date(),
				"@iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiIntrodução Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Primeiro Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Segundo Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Conclusão Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",ArtigoStatus.PUBLICADO, 
				 AutenticationBase64.passwordEncodeBase64(r.nextDouble() + "|" + "C-Sharp"), "C-Sharp","semFotoDestaque.png",
				"semFotoCard.png", a2, 3, cat3, s4);
		Artigo art7 = new Artigo(null, "Setimo Artigo", new Date(),
				"@qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqwwwwwwwwwwwwwwIntrodução Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Primeiro Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Segundo Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Conclusão Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",ArtigoStatus.PUBLICADO, 
				 AutenticationBase64.passwordEncodeBase64(r.nextDouble() + "|" + "c#"), "C#", "semFotoDestaque.png",
				"semFotoCard.png", a2, 2, cat3, s5);
		Artigo art8 = new Artigo(null, "Oitavo Artigo 1", new Date(),
				"@Iwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwntrodução Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Primeiro Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Segundo Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Conclusão Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",ArtigoStatus.PUBLICADO, 
				 AutenticationBase64.passwordEncodeBase64(r.nextDouble() + "|" + "MCI"),"MCI", "semFotoDestaque.png",
				"semFotoCard.png", a2, 1, cat3, s6);

		Artigo art119 = new Artigo(null, "Vai na Fé I Artigo 11", new Date(),
				"@Vai na Fé 3333333Introdução Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Primeiro Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Segundo Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Conclusão Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",ArtigoStatus.PUBLICADO, 
				 AutenticationBase64.passwordEncodeBase64(r.nextDouble() + "|" + "React"),"React", "semFotoDestaque.png",
				"semFotoCard.png", a2, 1, cat1, null);
		Artigo art9 = new Artigo(null, "Oitavo I Artigo 11", new Date(),
				"@33333333333333333333333333333333333333Introdução Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Primeiro Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Segundo Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Conclusão Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",ArtigoStatus.PUBLICADO, 
				 AutenticationBase64.passwordEncodeBase64(r.nextDouble() + "|" + "React"),"React", "semFotoDestaque.png",
				"semFotoCard.png", a2, 1, cat1, null);
		Artigo art10 = new Artigo(null, "Ransomware", new Date(),
				"@Um ataque ransomware é uma forma de ciberataque onde os hackers criptografam arquivos importantes do sistema ou rede de uma vítima e exigem um resgate para fornecer a chave de descriptografia. Este tipo de ataque é frequentemente feito através de engenharia social, como e-mails de phishing, para instalar o malware em um sistema.",
				"@Uma vez instalado, o malware pode rapidamente se espalhar por uma rede, criptografando centenas ou milhares de arquivos valiosos. Os hackers então exigem o pagamento de uma quantia de dinheiro, geralmente em moedas digitais, como Bitcoin, para fornecer a chave de descriptografia.",
				"@É importante destacar que o pagamento do resgate não garante necessariamente a recuperação dos dados criptografados, e na verdade, pode incentivar os criminosos a realizar mais ataques. Além disso, pagar o resgate também não remove o malware do sistema, deixando a vítima vulnerável a futuros ataques.",
				"@Por isso, é importante ter medidas de segurança eficazes, como backups regulares e manter softwares de segurança atualizados, para minimizar o risco de um ataque ransomware bem-sucedido e para minimizar os danos em caso de ataque.",
				ArtigoStatus.PUBLICADO,  AutenticationBase64.passwordEncodeBase64(r.nextDouble() + "|" + "VIRUS"),"Ransomware", "ransomware.jpg",
				"ransomware.jpg", a2, 1, cat4, s14);
		Artigo art11 = new Artigo(null, "Trojan", new Date(),
				"@Um trojan virus é um tipo de malware que se disfarça como um aplicativo legítimo, mas esconde sua verdadeira natureza maliciosa. Ele é chamado de \"trojan\" porque se aproveita da confiança do usuário para se infiltrar em um sistema.",
				"@Quando um trojan é executado, ele pode realizar várias ações maliciosas, como coletar informações pessoais, como senhas e números de cartões de crédito, instalar software adicional malicioso, como spyware ou adware, ou até mesmo permitir que o invasor tenha acesso remoto ao sistema infectado.",
				"@Os trojans geralmente são distribuídos através de engenharia social, como links maliciosos em e-mails ou downloads de arquivos suspeitos. Por isso, é importante tomar medidas de precaução ao abrir e-mails ou fazer downloads de fontes desconhecidas.",
				"@Para se proteger de ataques de trojan, é importante manter o sistema e os aplicativos atualizados, usar software antivírus eficaz, fazer backups regulares de seus dados e ser cauteloso ao abrir e-mails ou fazer downloads de fontes suspeitas.",
				ArtigoStatus.PUBLICADO, AutenticationBase64.passwordEncodeBase64(r.nextDouble() + "|" + "VIRUS"), "VIRUS", "troya.jpg",
				"troya.jpg", a2, 1, cat4, s15);
		Artigo art12 = new Artigo(null, "Backdoor", new Date(),
				"@Um ataque backdoor é um tipo de invasão de segurança na qual um invasor instala um \"portão traseiro\" secreto em um sistema ou aplicativo para obter acesso não autorizado aos dados ou recursos da vítima. Esse acesso geralmente permite que o invasor execute tarefas maliciosas, como monitorar ou manipular dados, instalar software adicional malicioso ou até mesmo controlar o sistema infectado remotamente.",
				"@Os backdoors geralmente são instalados através de exploits ou outras vulnerabilidades de segurança, ou até mesmo por meio de software malicioso disfarçado como um aplicativo legítimo. Eles também podem ser introduzidos pelo próprio fabricante do sistema ou aplicativo como uma forma de permitir acesso de suporte técnico, mas sem autorização adequada, isso pode ser perigoso.",
				"@Para proteger-se de ataques backdoor, é importante manter o sistema e aplicativos atualizados, usar software antivírus eficaz e ser cauteloso ao instalar aplicativos de fontes desconhecidas ou suspeitas. Além disso, é importante monitorar o tráfego de rede e verificar o sistema regularmente em busca de atividade suspeita.",
				"@Conclusão Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				ArtigoStatus.PUBLICADO, AutenticationBase64.passwordEncodeBase64(r.nextDouble() + "|" + "VIRUS"), "VIRUS", "alert.jpg",
				"alert.jpg", a2, 1, cat4, s16);
		Artigo art13 = new Artigo(null, "Fluxion", new Date(),
				"@Um ataque Fluxion é um tipo de ataque de engenharia social que visa obter informações confidenciais, como senhas, de usuários de redes Wi-Fi protegidas por WPA/WPA2. Esse tipo de ataque usa um processo de falsificação de autenticação para induzir as vítimas a se conectarem a um ponto de acesso Wi-Fi malicioso criado pelo invasor.",
				"@O ataque começa com a criação de um ponto de acesso Wi-Fi falso que imita a rede de destino. Quando um usuário se conecta a esse ponto de acesso, o Fluxion captura as informações de autenticação do usuário e, em seguida, utiliza-as para se conectar à rede real sem que o usuário perceba. Depois disso, o invasor pode capturar todo o tráfego de rede da vítima e interceptar informações confidenciais, como senhas.",
				"@Para se proteger de ataques como o Fluxion, é importante utilizar senhas fortes e seguras para suas redes Wi-Fi, atualizar regularmente o firmware do roteador e usar software de segurança para proteger seus dispositivos contra ameaças cibernéticas.",
				"@Além disso, é importante estar atento a sinais de que a rede Wi-Fi pode estar sendo hackeada, como conexões lentas ou instáveis ou problemas de autenticação. @É importante ressaltar que o uso de ataques Fluxion é ilegal e pode resultar em processos criminais e civis. Além disso, é importante que os usuários tomem medidas de segurança adequadas para proteger suas redes Wi-Fi, como o uso de senhas fortes e atualização regular dos dispositivos de rede com as últimas correções de segurança.",
				ArtigoStatus.PUBLICADO, AutenticationBase64.passwordEncodeBase64(r.nextDouble() + "|" + "VIRUS"), "FLUXION", "fluxion.jpg",
				"fluxion.jpg", a2, 1, cat4, s17);

		Artigo art14 = new Artigo(null, "Oitavo V Artigo ertereweee", new Date(),
				"@7777777777777777777777777777777777777777777777777777777Introdução Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Primeiro Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Segundo Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Conclusão Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				ArtigoStatus.PUBLICADO, 
				 AutenticationBase64.passwordEncodeBase64(r.nextDouble() + "|" + "Spring"),"Spring Boot", "semFotoDestaque.png",
				"semFotoCard.png", a2, 1, cat2, null);
		Artigo art15 = new Artigo(null, "Oitavo V Artigo 0000000000000", new Date(),
				"@Immmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmntrodução Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Primeiro Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Segundo Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Conclusão Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				ArtigoStatus.PUBLICADO,  AutenticationBase64.passwordEncodeBase64(r.nextDouble() + "|" + "Kali"), "Kali","semFotoDestaque.png",
				"semFotoCard.png", a2, 1, cat2, null);
		Artigo art16 = new Artigo(null, "Oitavo V Artigo 010202010", new Date(),
				"@Flavio ROGERIOIntrodução Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Primeiro Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Segundo Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Conclusão Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",ArtigoStatus.PUBLICADO, 
				 AutenticationBase64.passwordEncodeBase64(r.nextDouble() + "|" + "Node"),"Node.JS", "semFotoDestaque.png",
				"semFotoCard.png", a2, 1, cat2, null);
		Artigo art17 = new Artigo(null, "Oitavo V Artigo 000122222222", new Date(),
				"@cRAQUE NETO Introdução Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Primeiro Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Segundo Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Conclusão Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",ArtigoStatus.PUBLICADO, 
				 AutenticationBase64.passwordEncodeBase64(r.nextDouble() + "|" + "React"),"React", "semFotoDestaque.png",
				"semFotoCard.png", a2, 1, cat2, null);
		Artigo art18 = new Artigo(null, "Oitavo V Artigo FLAVIO", new Date(),
				"@9999999999999999999999999999999999999999Introdução Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Primeiro Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Segundo Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Conclusão Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",ArtigoStatus.PUBLICADO, 
				AutenticationBase64.passwordEncodeBase64(r.nextDouble() + "|" + "Windows"), "Windows","semFotoDestaque.png",
				"semFotoCard.png", a2, 1, cat2, null);
		Artigo art19 = new Artigo(null, "Oitavo V Artigo MMMMMMMMMMMMM", new Date(),
				"@ITTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTntrodução Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Primeiro Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Segundo Paragrafo Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
				"@Conclusão Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. @It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",ArtigoStatus.PUBLICADO, 
				 AutenticationBase64.passwordEncodeBase64(r.nextDouble() + "|" + "Twitter"),"Twitter", "semFotoDestaque.png",
				"semFotoCard.png", a2, 1, cat2, null);

		artigoRepository.saveAll(Arrays.asList(art1, art2, art3, art4, art5, art6, art8, art7, art9, art119, art10, art11,
				art12, art13, art14, art15, art16, art17, art18, art19));
		/*
		 * #alt Alteração da Modelagem quanto ao @ManyToMany art1.setCategorias(cat1);
		 * art1.setCategorias(cat2); art1.setCategorias(cat3); art2.setCategorias(cat3);
		 * art3.setCategorias(cat3); art4.setCategorias(cat2); art5.setCategorias(cat2);
		 * art6.setCategorias(cat1); art6.setCategorias(cat2); art7.setCategorias(cat2);
		 * art8.setCategorias(cat3);
		 * 
		 * art9.setCategorias(cat4); art10.setCategorias(cat4);
		 * art11.setCategorias(cat4); art12.setCategorias(cat4);
		 * art13.setCategorias(cat4);
		 */

		Comentario c1 = new Comentario(null, "Adalberto", "LOREM IPSUM", new Date(), art1);
		Comentario c2 = new Comentario(null, "Ana", "LOREM IPSUM, LOREM IPSUM", new Date(), art2);
		Comentario c3 = new Comentario(null, "Tania", "LOREM IPSUM, LOREM IPSUM, LOREM IPSUM", new Date(), art1);
		Comentario c4 = new Comentario(null, "LUCAS JUCA", "Hibernate @OneToOne @NotNull", new Date(), art1);
		comentarioReposiroty.saveAll(Arrays.asList(c1, c2, c3, c4));
		Tag tg1 = new Tag(null, "JAVA", art1);
		Tag tg2 = new Tag(null, "LINUX", art2);
		tagRepository.saveAll(Arrays.asList(tg1, tg2));

	}

}
